sbatch submit/submit_0k.sh
sbatch submit/submit_1k.sh
sbatch submit/submit_2k.sh
sbatch submit/submit_4k.sh
sbatch submit/submit_8k.sh
sbatch submit/submit_16k.sh
sbatch submit/submit_32k.sh
sbatch submit/submit_64k.sh
sbatch submit/submit_96k.sh
sbatch submit/submit_128k.sh